### ISSUE TITLE
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by NullVoxPopuli** [codemirror/buildhelper#7]
This error occurs when trying to parse the `.grammar` file:

Reproduction here: https://stackblitz.com/edit/node-rwuxbu?file=gjs%2Findex.html,gjs%2Ftest%2Fpreview.ts,package.json,gjs%2Fpackage.json,gjs%2Fsrc%2Findex.ts,pnpm-workspace.yaml,gjs%2Fsrc%2Fsyntax.grammar,gjs%2Fsrc%2Ftokens.ts,gjs%2Fsrc%2Fsyntax.grammar.terms.d.ts,dev%2Fwatch.cjs&file=src%2Findex.ts,src%2Ftokens.ts

steps:
  - wait for blitz to boot
  - open a new terminal - 
![image](https://user-images.githubusercontent.com/199018/236646690-899de18a-e376-4816-86d0-781ff380e46f.png)
(via the plus button)
 - `cd gjs`
 - run `pnpm build`
 - see error:
 ```
❯ pnpm build

> gjs@0.0.0-alpha.0 build /home/projects/node-rwuxbu/gjs
> cm-buildhelper src/index.ts

Unused rule 'Text' (/home/projects/node-rwuxbu/gjs/src/syntax.grammar 15:2)
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
    at error (/home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:198:30)
    at error (/home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12560:16)
    at tryParse (/home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12937:25)
    at setSource (/home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12842:24)
    at addModuleSource (/home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:22090:20) {
  code: 'PARSE_ERROR',
  parserError: [pp$4.raise@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:19551:13
  pp.getTokenFromCode@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:21213:8
  pp.readToken@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:20900:15
  pp.nextToken@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:20891:15
  parse@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:16673:8
  parse@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:16724:35
  contextParse@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:23090:38
  tryParse@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12927:31
  setSource@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12842:24
  addModuleSource@file:///home/projects/node-rwuxbu/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:22090:20
  ] {
    pos: 0,
    loc: Position { line: 1, column: 0 },
    raisedAt: 0
  },
  id: '/home/projects/node-rwuxbu/gjs/src/syntax.grammar',
  pos: 0,
  loc: {
    column: 0,
    file: '/home/projects/node-rwuxbu/gjs/src/syntax.grammar',
    line: 1
  },
  frame: '1: @top Document { entity* } \r\n   ^\n2: \r\n3: entity {\r',
  watchFiles: [
    '/home/projects/node-rwuxbu/gjs/src/index.d.ts',
    '/home/projects/node-rwuxbu/gjs/src/syntax.grammar'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by NullVoxPopuli** [comment]
Adding a `syntax.grammar.d.ts` file with the contents:
```ts
import { Parser } from '@lezer/common';

export declare const parser: Parser;
```
resolved the error. 🤷

**Comment by NullVoxPopuli** [comment]
I don't think this should be closed, the DX here is pretty bad (rollup treating the grammar file as a js script, and not saying why, etc)
Is there maybe a linter tool that could check for these weird sorts of conventions that are required?

**Comment by marijnh** [comment]
The build helper is a thing I use to build the library packages, not a tool that aims to have good UX. Sorry, but I don't have the energy to provide support for every hack I write.

**Comment by NullVoxPopuli** [comment]
As a consumer of codemirror/lezer should I be using a different technique for building? maybe with some specific rollup config / not using your personal build helpers?

**Comment by marijnh** [comment]
Probably. See for example https://github.com/codemirror/lang-example
